In [1]:
import numpy as np

In [2]:
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [4]:
char_arr2=np.array(["Supervised","unSupervised","SeMi-Supervised","ReinfOrced"])
low_arr=np.char.lower(char_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforced'],
      dtype='<U15')

In [5]:
cleaned_arr=np.char.replace(low_arr,"-"," ")
cleaned_arr

array(['supervised', 'unsupervised', 'semi supervised', 'reinforced'],
      dtype='<U15')

In [6]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [7]:
array1.dtype

dtype('int32')

In [8]:
char_arr.dtype

dtype('<U1')

In [9]:
char_arr2.dtype

dtype('<U15')

In [10]:
array8=np.array([1,2,3,4,5],dtype='S')
array8

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [15]:
arr8=np.array([1,2,3,4,5],dtype='f')
arr8

array([1., 2., 3., 4., 5.], dtype=float32)

In [12]:
arr9=np.array([1,2,3,4,5],dtype='float32')
arr9

array([1., 2., 3., 4., 5.], dtype=float32)

In [17]:
arrcon=arr8.astype('i')
arrcon

array([1, 2, 3, 4, 5], dtype=int32)

In [18]:
charcon=char_arr.astype('i')
charcon

ValueError: invalid literal for int() with base 10: 'a'

In [20]:
ars1=np.ones(3)
ars1

array([1., 1., 1.])

In [21]:
ars2=np.zeros(3)
ars2

array([0., 0., 0.])

In [22]:
ars3=np.random.random(3)
ars3

array([0.07752679, 0.18298808, 0.3704065 ])

In [23]:
numone=np.ones((2,2),dtype=int)
numone

array([[1, 1],
       [1, 1]])

In [25]:
numsone=np.ones((3,2))
numsone

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
numzero=np.zeros((3,3))
numzero.astype('i')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [27]:
dimones=np.ones((4,3,2))
dimones

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [31]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[8,9,10]])
addition=ar1+ar2
print("addition: \n",addition)
print("subtraction: \n",ar1-ar2)
print("multiplication: \n",ar1*ar2)
print("division: \n",ar1/ar2)

addition: 
 [[ 6  8 10]
 [12 14 16]]
subtraction: 
 [[-4 -4 -4]
 [-4 -4 -4]]
multiplication: 
 [[ 5 12 21]
 [32 45 60]]
division: 
 [[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


In [32]:
power=np.power(ar1,ar2)
print("power: \n",power)

power: 
 [[       1       64     2187]
 [   65536  1953125 60466176]]


In [33]:
arr2d=np.array([[1,2,3],[4,5,6]])
arr1d=np.array([10,20,22])
result=arr2d+arr1d
result

array([[11, 22, 25],
       [14, 25, 28]])

In [35]:
range_array=np.arange(0,10,3)
range_array

array([0, 3, 6, 9])

In [36]:
a=np.random.randint(low=1,size=5)
a

array([0, 0, 0, 0, 0])

In [37]:
b=np.random.randint(low=1,high=6,size=(2,3))
b

array([[2, 1, 2],
       [5, 5, 1]])

In [38]:
np.concatenate([ar1,ar2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [39]:
flatarr=ar1.flatten()
flatarr

array([1, 2, 3, 4, 5, 6])

In [40]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [43]:
np.info(np.ndim)

 ndim(a)

Return the number of dimensions of an array.

Parameters
----------
a : array_like
    Input array.  If it is not already an ndarray, a conversion is
    attempted.

Returns
-------
number_of_dimensions : int
    The number of dimensions in `a`.  Scalars are zero-dimensional.

See Also
--------
ndarray.ndim : equivalent method
shape : dimensions of array
ndarray.shape : dimensions of array

Examples
--------
>>> np.ndim([[1,2,3],[4,5,6]])
2
>>> np.ndim(np.array([[1,2,3],[4,5,6]]))
2
>>> np.ndim(1)
0


In [42]:
np.info(np.random.randint)

randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.randint`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  I